export const recipes = [
  {
    uuid: 1,
    name: "Baked Salmon",
    ingredients: [
      { name: "Salmon", amount: 1, measurement: "l lb" },
      { name: "Pine Nuts", amount: 1, measurement: "cup" },
      { name: "Butter Lettuce", amount: 2, measurement: "cups" },
      { name: "Yellow Squash", amount: 1, measurement: "med" },
      { name: "Olive Oil", amount: 0.5, measurement: "cup" },
      { name: "Garlic", amount: 3, measurement: "cloves" },
    ],
    steps: [
      "Preheat the oven to 350 degrees.",
      "Spread the olive oil around a glass baking dish.",
      "Add the yellow squash and place in the oven for 30 mins.",
      "Add the salmon, garlic, and pine nuts to the dish.",
      "Bake for 15 minutes.",
      "Remove from oven. Add the lettuce and serve.",
    ],
    rating: 4,
  },
  {
    uuid: 2,
    name: "Fish Tacos",
    ingredients: [
      { name: "Whitefish", amount: 1, measurement: "l lb" },
      { name: "Cheese", amount: 1, measurement: "cup" },
      { name: "Iceberg Lettuce", amount: 2, measurement: "cups" },
      { name: "Tomatoes", amount: 2, measurement: "large" },
      { name: "Tortillas", amount: 3, measurement: "med" },
      { name: "Corn", amount: 1, measurement: "can" },
    ],
    steps: [
      "Cook the fish on the grill until cooked through.",
      "Place the fish on the 3 tortillas.",
      "Top them with lettuce, tomatoes, corn and cheese.",
    ],
    rating: 2,
  },
  {
    uuid: 3,
    name: "Chicken Noodle Soup",
    ingredients: [
      { name: "Extra virgin olive oil", amount: 3, measurement: "tablespoons" },
      { name: "Onion", amount: 1, measurement: "yellow" },
      { name: "Carots", amount: 2, measurement: "medium" },
      { name: "Celery", amount: 2, measurement: "stalks" },
      { name: "Egg noodles", amount: 1, measurement: "package" },
      { name: "Cooked chicken", amount: 1, measurement: "cup" },
    ],
    steps: [
      "Chop and saute onion, carrots and celery in olive oil until soft.",
      "Add chicken broth and bring to boil",
      "Add egg noodles and cook until soft",
      "Add chicken",
    ],
    rating: 5,
  },
];
